### ISSUE TITLE
Puck tracker doesn't always capture puck

### ISSUE THREAD

**Issue by wsh32** [wsh32/airhockey#28]
Depending on lighting, the puck isnt always tracked.

Case where it works:
![image](https://user-images.githubusercontent.com/8334837/139966400-71102f90-fe89-4371-a297-2e21086bb64f.png)

Case where it doesn't work:
![image](https://user-images.githubusercontent.com/8334837/139966353-020e97ce-31e5-4451-a6f9-485b72fcaa2c.png)

We may need to either figure out a way to have consistent lighting or recalibrate the color tracker. The HSV values are currently found in `src/airhockey_vision/config/detect_green.yaml`.

**Comment by wsh32** [comment]
Also sometimes it doesnt capture the center correctly
![image](https://user-images.githubusercontent.com/8334837/139966636-b55a5df1-d51e-4963-a285-ad1e04fe46a8.png)

**Comment by wsh32** [comment]
[images.zip](https://github.com/wsh32/airhockey/files/7464582/images.zip)

Heres a bunch of test images

**Comment by iserrato** [comment]
Lighting would help with this issue significantly

**Comment by wsh32** [comment]
switched to a matte blue vinyl cut puck: 
![image](https://user-images.githubusercontent.com/8334837/141882953-cb80ec42-5257-4a93-844a-61881a5bc30d.png)

Looks like this issue is mostly resolved. Note that there are a couple of odd cases where the system picks up the blue "Air" text instead of the puck, but this was fixed by coloring in that light blue with a black sharpie
